<?php

namespace Phlegmatic\Tester\Tests\Mock\Adapter\OutputResultsRunner;


use Phlegmatic\Tester\Adapter\OutputResultsRunner\OutputResultsTester;

class MockOutputResultsTester extends OutputResultsTester
{


    public function assert(bool $result, string $why): void
    {
        parent::assert($result, $why); // TODO: Change the autogenerated stub
    }

    public function expect(string $exception_type, callable $when, string $why): void
    {
        parent::expect($exception_type, $when, $why); // TODO: Change the autogenerated stub
    }

    public function getSuccessCount(): int
    {
        return parent::getSuccessCount(); // TODO: Change the autogenerated stub
    }
}
